/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burgersrus.ui;

import javax.swing.JOptionPane;
/**
 *
 * @author Chris
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    
    // Models
    private burgersrus.model.Burger currentBurger = new burgersrus.model.Burger();
    
    public MainUI() {
        initComponents();
        
         // group radios so only one is selected
         javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();
         group.add(rbSingleBurger);
         group.add(rbDoubleBurger);
         
         rbSingleBurger.setSelected(true);  //Default Single
         getOrderQuantity.setText("1");     //Default Quantity
        
         // Default Fields
         currentBurger.setType("Single");
         currentBurger.setQuantity(1);
         currentBurger.setCheese(false);
         currentBurger.setBacon(false);
         currentBurger.setMeal(false);
         
         updateItemPriceField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        rbDoubleBurger = new javax.swing.JRadioButton();
        rbSingleBurger = new javax.swing.JRadioButton();
        cbAddCheese = new javax.swing.JCheckBox();
        cbAddBacon = new javax.swing.JCheckBox();
        cbMakeAMeal = new javax.swing.JCheckBox();
        lblAddOns = new javax.swing.JLabel();
        setItemPrice = new javax.swing.JTextField();
        getOrderQuantity = new javax.swing.JTextField();
        setOrderTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplayReceipt = new javax.swing.JTextArea();
        lblOrderQuantity = new javax.swing.JLabel();
        lblItemPrice = new javax.swing.JLabel();
        lblOrderTotal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuOrder = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbDoubleBurger.setText("Double");
        rbDoubleBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoubleBurgerActionPerformed(evt);
            }
        });

        rbSingleBurger.setText("Single");
        rbSingleBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSingleBurgerActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(rbDoubleBurger, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rbSingleBurger, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDoubleBurger)
                    .addComponent(rbSingleBurger))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbSingleBurger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDoubleBurger)
                .addContainerGap())
        );

        cbAddCheese.setText("Add Cheese");

        cbAddBacon.setText("Add Bacon");

        cbMakeAMeal.setText("Make it a Meal");

        lblAddOns.setText("Add Ons:");

        getOrderQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOrderQuantityActionPerformed(evt);
            }
        });

        setOrderTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOrderTotalActionPerformed(evt);
            }
        });

        txtDisplayReceipt.setEditable(false);
        txtDisplayReceipt.setColumns(20);
        txtDisplayReceipt.setRows(5);
        jScrollPane1.setViewportView(txtDisplayReceipt);

        lblOrderQuantity.setText("Order Quantity:");

        lblItemPrice.setText("Item Price:");
        lblItemPrice.setToolTipText("");

        lblOrderTotal.setText("Order Total:");

        MenuFile.setText("File");
        jMenuBar1.add(MenuFile);

        MenuOrder.setText("Edit");
        jMenuBar1.add(MenuOrder);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAddBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAddCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMakeAMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblItemPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblAddOns)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 157, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrderTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrderQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 88, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(lblAddOns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAddCheese))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAddBacon)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMakeAMeal)
                    .addComponent(getOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderQuantity))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemPrice))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setOrderTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOrderTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setOrderTotalActionPerformed

    private void getOrderQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOrderQuantityActionPerformed
        // TODO add your handling code here:
        String input = getOrderQuantity.getText().trim();
        
        // Check if user typed anything.
        if (input.isEmpty()) 
        {
            getOrderQuantity.setText("1");
        }
        
        try 
        {
            int quantity = Integer.parseInt(input);
            
            // isGreater than zero?
            if (quantity <= 0)
            {
                JOptionPane.showMessageDialog
                    (
                        null,
                        "Quantity must be a Number greater then zero",
                        "Invalid Int or Quantity",
                        JOptionPane.ERROR_MESSAGE
                    );
                getOrderQuantity.setText("1");
                
            } else {
                txtDisplayReceipt.setText("getOrderQuantityActionPerformed text set");
            }
        } catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog
            (
                null,
                "Please enter a valid number.",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_getOrderQuantityActionPerformed

    private void rbSingleBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSingleBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSingleBurgerActionPerformed

    private void rbDoubleBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoubleBurgerActionPerformed
        updateItemPriceField();
    }//GEN-LAST:event_rbDoubleBurgerActionPerformed
    
    private void updateItemPriceField() {
        // calculate price of one item only
        String price = new java.text.DecimalFormat("0.00")
            .format(currentBurger.calculateItemCost());
        setItemPrice.setText(price);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuOrder;
    private javax.swing.JCheckBox cbAddBacon;
    private javax.swing.JCheckBox cbAddCheese;
    private javax.swing.JCheckBox cbMakeAMeal;
    private javax.swing.JTextField getOrderQuantity;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOns;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JLabel lblOrderQuantity;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JRadioButton rbDoubleBurger;
    private javax.swing.JRadioButton rbSingleBurger;
    private javax.swing.JTextField setItemPrice;
    private javax.swing.JTextField setOrderTotal;
    private javax.swing.JTextArea txtDisplayReceipt;
    // End of variables declaration//GEN-END:variables
}
